"""Checkpoint save/load with sha256 + provenance sidecar and legacy key remap.

Save: every checkpoint gets two siblings —
    <ckpt>.json.sha256          standard "HEX  filename" digest line
    <ckpt>.provenance.json      FULL provenance sidecar (C4: model + provider
                                note, dspy/gepa/litellm versions, dataset +
                                eval blocks when supplied, not_a_claim_of list,
                                empty re_measurements). Generated by
                                sidecar.build_sidecar; BACKWARD-COMPATIBLE with
                                the C2 stub (every stub field is still present
                                with the same meaning). save_checkpoint passes
                                through dataset/eval/not_a_claim_of so a compile
                                writes the full record in one shot.

Load: dspy's native Module.load() first; on failure, the key-remap path
ported from the production optimizer (gate.* prefix strip for
LensGateWrapper saves, BestOfN `.module` remap for pre/post-BestOfN
checkpoints), filtered to the target module's current parameters.
"""
import hashlib
import json
from pathlib import Path

from .config import Profile


def sha256_file(path: str | Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def save_checkpoint(module, path: str | Path, *, profile: Profile,
                    train_size: int, val_size: int, extra: dict | None = None,
                    dataset_path: str | Path | None = None,
                    eval_results_path: str | Path | None = None,
                    extra_not_a_claim_of: list[str] | None = None) -> dict:
    """Save a dspy module checkpoint + sha256 sibling + FULL provenance sidecar.

    Returns the sidecar dict (also written to <ckpt>.provenance.json). The
    sidecar is the C4 full record (sidecar.build_sidecar), backward-compatible
    with the C2 stub's fields. dataset_path/eval_results_path enrich the
    dataset/eval blocks when available at compile time; both are optional so a
    bare save still produces a complete (if leaner) sidecar.
    """
    from .sidecar import build_sidecar  # deferred: avoid import cycle at module load

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    module.save(str(path))
    digest = sha256_file(path)

    sha_path = Path(str(path) + ".sha256")
    sha_path.write_text(f"{digest}  {path.name}\n", encoding="utf-8")

    sidecar = build_sidecar(
        path, profile=profile, train_size=train_size, val_size=val_size,
        dataset_path=dataset_path, eval_results_path=eval_results_path,
        extra_not_a_claim_of=extra_not_a_claim_of, extra=extra)
    prov_path = path.with_suffix(".provenance.json")
    prov_path.write_text(json.dumps(sidecar, indent=2) + "\n", encoding="utf-8")
    return sidecar


def _candidate_keys(param_name: str) -> list[str]:
    """Checkpoint-key candidates for a module parameter, in priority order.

    Covers (ported from the production optimizer's remap):
      - exact match
      - `gate.` prefix strip/add (LensGateWrapper saves vs bare LensGate)
      - BestOfN `.module` strip/add (checkpoints saved before/after
        Truth/Extrapolation were wrapped in BestOfN, and fast_mode gates)
    """
    base = param_name[5:] if param_name.startswith("gate.") else param_name
    variants = [param_name, base, "gate." + base]
    extended = []
    for v in variants:
        if v.endswith(".module"):
            extended.append(v[:-len(".module")])
            extended.append("gate." + v[:-len(".module")] if not v.startswith("gate.")
                            else v[5:-len(".module")])
        else:
            extended.append(v + ".module")
            extended.append(("gate." + v + ".module") if not v.startswith("gate.")
                            else v[5:] + ".module")
    out: list[str] = []
    for v in variants + extended:
        if v and v not in out:
            out.append(v)
    return out


def load_checkpoint(module, path: str | Path, *, log=print) -> dict:
    """Load a checkpoint into `module`, remapping legacy keys when needed.

    Returns a report dict:
        remapped: bool — True when the key-remap path ran
        loaded:   param names that received checkpoint state
        missing:  current params with no matching checkpoint key (kept as-is)
        stale:    checkpoint keys matched by no current param (skipped)

    Raises ConfigError-free ValueError when NOTHING matches (a wrong file is
    a hard error, never a silent fresh start).
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Checkpoint not found: {path}")
    try:
        module.load(str(path))
        return {"remapped": False, "loaded": [n for n, _ in module.named_parameters()],
                "missing": [], "stale": []}
    except Exception as e:  # KeyError on renamed keys, etc. — try remap
        log(f"Direct checkpoint load failed ({e!r}); attempting key remap...")

    state = json.loads(path.read_text())
    ckpt_keys = {k: v for k, v in state.items() if k != "metadata"}
    loaded, missing = [], []
    used_keys: set[str] = set()

    for name, param in module.named_parameters():
        match = next((c for c in _candidate_keys(name) if c in ckpt_keys), None)
        if match is None:
            missing.append(name)
            continue
        param.load_state(ckpt_keys[match])
        loaded.append(name)
        used_keys.add(match)

    stale = sorted(set(ckpt_keys) - used_keys)
    if not loaded:
        raise ValueError(
            f"No checkpoint keys matched any module parameter in {path} — "
            f"refusing to silently start fresh (checkpoint keys: {sorted(ckpt_keys)[:5]}...)"
        )
    msg = f"Loaded checkpoint with key remap: {path.name} ({len(loaded)} params"
    if stale:
        msg += f", skipped {len(stale)} stale keys"
    if missing:
        msg += f", {len(missing)} params left at defaults"
    log(msg + ")")
    return {"remapped": True, "loaded": loaded, "missing": missing, "stale": stale}
